### ISSUE TITLE
serverless is making calls to sp-notifications-and-metrics-v1.serverless-platform.com

### ISSUE THREAD

**Issue by kishorborate-a** [serverless/utils#208]
Hi,

In one of our project where we use serverless framework, we are not expecting to use analytics feature of the serverless. Still the framework is making calls to endpoint sp-notifications-and-metrics-v1.serverless-platform.com

How can I configure the serverless to prevent calls to this domain?

**Comment by medikoo** [comment]
@kishorborate-a see https://www.serverless.com/framework/docs/telemetry
