### ISSUE TITLE
Security Vulnerability with `semver` (via `make-dir` Transitive Dependency)

### ISSUE THREAD

**Issue by brianlenz** [serverless/utils#212]
`make-dir` `3.1.0` depends on `semver` `^6.0.0` which has a vulnerability:

https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

The solution is to upgrade `make-dir` to `4.0.0` which updates `semver` to `^7.5.3`, which doesn't have the vulnerability.

**Comment by medikoo** [comment]
@brianlenz thanks for reporting. PR which upgrades `make-dir` is welcome!

**Comment by brianlenz** [comment]
@medikoo I'm not sure what your development or PR processes are, but I've created #213. It passes `lint` and `test`. `make-dir` is only used once, and the upgrade doesn't appear to affect the particular interface being used. Please let me know if there is anything that needs to be changed or that you'd like done differently! Thank you 🙏
