### ISSUE TITLE
cloudformation-schema doc update (?)

### ISSUE THREAD

**Issue by jfgordon2** [serverless/utils#98]
Currently in the [cloudformationSchema](https://github.com/serverless/utils/blob/master/docs/cloudformation-schema.md) doc, it states the import should be as:
```javascript
const cloudFormationSchema = require('@serverless/utils/cloudformationSchema');
```

But it seems to export directly from the file, so it requires a user to do:
```javascript
const cloudFormationSchema = require("@serverless/utils/cloudformation-schema") 
```

I'm guessing this is unintentional so I'm reporting it as a bug, though it may just need a doc update.

**Comment by medikoo** [comment]
@jfgordon2 great thanks for reporting!

It's a definitive error on documentation side, have you considered opening PR with a fix?

**Comment by jfgordon2** [comment]
Opened PR #99 - thanks @medikoo!
